#!/usr/bin/env python
# coding: utf-8
import os

import requests as r

import job_detail

URL = "https://www.yes123.com.tw/admin/job_refer_list.asp"

data = {'_mu_chkbox_2': '',
 '_mu_chkbox_3': '',
 '_mu_edu_1': '',
 '_mu_edu_2': '',
 '_mu_edu_3': '',
 '_mu_edu_4': '',
 '_mu_edu_5': '',
 '_mu_edu_6': '',
 '_mu_edu_7': '',
 '_mu_job_1': '',
 '_mu_lang_1': '',
 '_mu_lang_2': '',
 '_mu_lang_3': '',
 '_mu_psn_1': '',
 '_mu_sc_1': '',
 '_mu_sc_2': '',
 '_mu_se_1': '',
 '_mu_sf_1': '',
 '_mu_vc_1': '',
 '_mu_vc_2': '',
 '_mu_vc_3': '',
 '_mu_vc_4': '',
 '_mu_wk_1': '',
 '_mu_wk_2': '',
 '_mu_wk_3': '',
 '_mu_wk_4': '',
 '_mu_wk_5': '',
 '_mu_year_1': '',
 '_mu_year_2': '',
 '_rdo_1': '1',
 '_rdo_2': '1',
 'find_cert_mode1': '',
 'find_cert_mode2': '',
 'find_cert_mode3': '',
 'find_cert_mode4': '',
 'find_cert_mode5': '',
 'find_indy_mode1': '',
 'find_indy_mode10': '',
 'find_indy_mode2': '',
 'find_indy_mode3': '',
 'find_indy_mode4': '',
 'find_indy_mode5': '',
 'find_indy_mode6': '',
 'find_indy_mode7': '',
 'find_indy_mode8': '',
 'find_indy_mode9': '',
 'find_job_mode1': '',
 'find_job_mode10': '',
 'find_job_mode2': '',
 'find_job_mode3': '',
 'find_job_mode4': '',
 'find_job_mode5': '',
 'find_job_mode6': '',
 'find_job_mode7': '',
 'find_job_mode8': '',
 'find_job_mode9': '',
 'find_key1': 'java',
 'find_key2': '',
 'find_key3': '',
 'find_map_mode1': '',
 'find_map_mode2': '',
 'find_map_mode3': '',
 'find_map_mode4': '',
 'find_metro_mode1': '',
 'find_metro_mode10': '',
 'find_metro_mode2': '',
 'find_metro_mode3': '',
 'find_metro_mode4': '',
 'find_metro_mode5': '',
 'find_metro_mode6': '',
 'find_metro_mode7': '',
 'find_metro_mode8': '',
 'find_metro_mode9': '',
 'find_sche_mode1': '',
 'find_sche_mode2': '',
 'find_sche_mode3': '',
 'find_sche_mode4': '',
 'find_sche_mode5': '',
 'find_scl_mode1': '',
 'find_scl_mode10': '',
 'find_scl_mode2': '',
 'find_scl_mode3': '',
 'find_scl_mode4': '',
 'find_scl_mode5': '',
 'find_scl_mode6': '',
 'find_scl_mode7': '',
 'find_scl_mode8': '',
 'find_scl_mode9': '',
 'find_se_work_mode1': '',
 'find_sf_subj_mode1': '',
 'find_subj_mode1': '',
 'find_subj_mode2': '',
 'find_subj_mode3': '',
 'find_sw_mode1': '',
 'find_sw_mode2': '',
 'find_sw_mode3': '',
 'find_sw_mode4': '',
 'find_sw_mode5': '',
 'find_work_mode1': '',
 'find_work_mode10': '',
 'find_work_mode2': '',
 'find_work_mode3': '',
 'find_work_mode4': '',
 'find_work_mode5': '',
 'find_work_mode6': '',
 'find_work_mode7': '',
 'find_work_mode8': '',
 'find_work_mode9': '',
 'find_zone_mode1': '',
 'find_zone_mode10': '',
 'find_zone_mode2': '',
 'find_zone_mode3': '',
 'find_zone_mode4': '',
 'find_zone_mode5': '',
 'find_zone_mode6': '',
 'find_zone_mode7': '',
 'find_zone_mode8': '',
 'find_zone_mode9': '',
 'job_show_type': 'L',
 'order_ascend': 'desc',
 'order_by': 'neworder',
 's_find_cert_mode1': '',
 's_find_cert_mode2': '',
 's_find_cert_mode3': '',
 's_find_cert_mode4': '',
 's_find_cert_mode5': '',
 's_find_indy_mode1': '',
 's_find_indy_mode10': '',
 's_find_indy_mode2': '',
 's_find_indy_mode3': '',
 's_find_indy_mode4': '',
 's_find_indy_mode5': '',
 's_find_indy_mode6': '',
 's_find_indy_mode7': '',
 's_find_indy_mode8': '',
 's_find_indy_mode9': '',
 's_find_job_mode1': '',
 's_find_job_mode10': '',
 's_find_job_mode2': '',
 's_find_job_mode3': '',
 's_find_job_mode4': '',
 's_find_job_mode5': '',
 's_find_job_mode6': '',
 's_find_job_mode7': '',
 's_find_job_mode8': '',
 's_find_job_mode9': '',
 's_find_metro_mode1': '',
 's_find_metro_mode10': '',
 's_find_metro_mode2': '',
 's_find_metro_mode3': '',
 's_find_metro_mode4': '',
 's_find_metro_mode5': '',
 's_find_metro_mode6': '',
 's_find_metro_mode7': '',
 's_find_metro_mode8': '',
 's_find_metro_mode9': '',
 's_find_sche_mode1': '',
 's_find_sche_mode2': '',
 's_find_sche_mode3': '',
 's_find_sche_mode4': '',
 's_find_sche_mode5': '',
 's_find_scl_mode1': '',
 's_find_scl_mode10': '',
 's_find_scl_mode2': '',
 's_find_scl_mode3': '',
 's_find_scl_mode4': '',
 's_find_scl_mode5': '',
 's_find_scl_mode6': '',
 's_find_scl_mode7': '',
 's_find_scl_mode8': '',
 's_find_scl_mode9': '',
 's_find_se_work_mode1': '',
 's_find_sf_subj_mode1': '',
 's_find_subj_mode1': '',
 's_find_subj_mode2': '',
 's_find_subj_mode3': '',
 's_find_sw_mode1': '',
 's_find_sw_mode2': '',
 's_find_sw_mode3': '',
 's_find_sw_mode4': '',
 's_find_sw_mode5': '',
 's_find_work_mode1': '',
 's_find_work_mode10': '',
 's_find_work_mode2': '',
 's_find_work_mode3': '',
 's_find_work_mode4': '',
 's_find_work_mode5': '',
 's_find_work_mode6': '',
 's_find_work_mode7': '',
 's_find_work_mode8': '',
 's_find_work_mode9': '',
 's_find_zone_mode1': '',
 's_find_zone_mode10': '',
 's_find_zone_mode2': '',
 's_find_zone_mode3': '',
 's_find_zone_mode4': '',
 's_find_zone_mode5': '',
 's_find_zone_mode6': '',
 's_find_zone_mode7': '',
 's_find_zone_mode8': '',
 's_find_zone_mode9': '',
 'search_feature': '',
 'search_from': 'joblist',
 'search_item': '1',
 'search_job2': '請選擇行業',
 'search_key_word': 'java',
 'search_multi_loc': '請選擇地區',
 'search_multi_loc2': '請選擇地區',
 'search_multi_loc3': '請選擇地區',
 'search_multi_loc4': '請選擇地區',
 'search_multi_loc5': '請選擇地區',
 'search_multi_loc6': '請選擇地區',
 'search_multi_loc7': '請選擇地區',
 'search_subj': '',
 'search_type': 'job',
 'search_work': '請選擇職務',
 'search_work2': '請選擇職務',
 'search_work3': '請選擇職務',
 'search_work4': '請選擇職務',
 'search_work6': '',
 'search_work7': '請選擇職務',
 'search_work8': '請選擇職務',
 'us_menu': ''}

strrec = 0
data['strrec'] = strrec

while True:
    print("[INFO] crawling strrec %s"%strrec)
    res = r.post(URL, data=data, headers={'User-Agent': ''})
    res.encoding = 'utf-8'
    if '查無資料' in res.text:
        break
    with open('./list_html/java_{}.html'.format(strrec), 'w') as f:
        f.write(res.text)
    strrec += 20
    data['strrec'] = strrec

os.system("cat ./list_html/java_*.html  | grep -Po 'job_refer_comp_job_detail2\.asp\?p_id=.*&job_id=\d*_\d*' | uniq > urls_uniq.txt")

job_detail.get_detail()
